package calcul;


/**
* calcul/calcul_montantsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./spec.idl
* mardi 7 décembre 2021 18 h 07 CET
*/

public interface calcul_montantsOperations 
{
  double calcul_ttc (double mt_ht, double taux);
} // interface calcul_montantsOperations
