package exo2;


/**
* exo2/calcul.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./server.idl
* mercredi 8 décembre 2021 01 h 25 CET
*/

public interface calcul extends calculOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface calcul
