package exo2;


/**
* exo2/calculOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./server.idl
* mercredi 8 décembre 2021 01 h 25 CET
*/

public interface calculOperations 
{
  void incrementer (org.omg.CORBA.IntHolder data);
  void decrementer (org.omg.CORBA.IntHolder data);
} // interface calculOperations
