package exo2;

/**
* exo2/calculHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./server.idl
* mercredi 8 décembre 2021 01 h 25 CET
*/

public final class calculHolder implements org.omg.CORBA.portable.Streamable
{
  public exo2.calcul value = null;

  public calculHolder ()
  {
  }

  public calculHolder (exo2.calcul initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = exo2.calculHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    exo2.calculHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return exo2.calculHelper.type ();
  }

}
