package exo1;


/**
* exo1/calculOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./server.idl
* mardi 7 décembre 2021 18 h 40 CET
*/

public interface calculOperations 
{
  void incrementer (org.omg.CORBA.IntHolder data);
  void decrementer (org.omg.CORBA.IntHolder data);
} // interface calculOperations
