package exo1;


/**
* exo1/calcul.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./server.idl
* mardi 7 décembre 2021 18 h 40 CET
*/

public interface calcul extends calculOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface calcul
